In [7]:
import pandas as pd
import numpy as np

In [89]:
import numpy as np
import pandas as pd

In [46]:
from keras.models import load_model
model1 = load_model('Model1')
model2 = load_model('Model2')

In [34]:
TRAIN = pd.read_csv('./DATA/full_train_met.csv')
TRAIN.head()

,year,month,day,delta_stage_max,lat,lon,distance_from_source,drainage_area,z_null,aet_12,...,snow_charact,snow_height,snow_coverage_station,temperature_240cm,precipitation_observed,precipitation_corrected,sunshine_hours,delta_temp20_80,delta_temp40_120,delta_temp160_320
0,1985,1,1,0.0,57.77,108.07,1140.0,92200,249.38,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1985,1,2,0.0,57.77,108.07,1140.0,92200,249.38,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1985,1,3,0.0,57.77,108.07,1140.0,92200,249.38,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1985,1,4,-1.0,57.77,108.07,1140.0,92200,249.38,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1985,1,5,0.0,57.77,108.07,1140.0,92200,249.38,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
TEST = pd.read_csv('./DATA/full_test_met.csv')
TEST.head()

,year,month,day,lat,lon,distance_from_source,drainage_area,z_null,aet_12,aet_11,...,snow_charact,snow_height,snow_coverage_station,temperature_240cm,precipitation_observed,precipitation_corrected,sunshine_hours,delta_temp20_80,delta_temp40_120,delta_temp160_320
0,1993,4,111,57.77,108.07,1140.0,92200,249.38,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1993,4,112,57.77,108.07,1140.0,92200,249.38,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1993,4,113,57.77,108.07,1140.0,92200,249.38,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1993,4,114,57.77,108.07,1140.0,92200,249.38,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1993,4,115,57.77,108.07,1140.0,92200,249.38,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
features = [
            'year',
            'month',
            'day',
            'lat',
            'lon',
            'distance_from_source',
            'drainage_area',
            'z_null',
            'aet_12',
            'aet_11',
            'aet_10',
            'aet_9',
            'aet_8',
            'aet_7',
            'aet_6',
            'aet_5',
            'aet_4',
            'aet_3',
            'aet_2',
            'aet_1',
            'Cm',
            'J',
            'K',
            'N',
            'O',
            'X',
            'Z',
            'horizontal_visibility',
            'cloud_amount_total',
            'cloud_base_altitude',
            'wind_direction',
            'wind_speed_aver',
            'soil_surface_temperature',
            'air_temperature',
            'water_vapour_partial_pressure',
            'relative_humidity',
            'vapour_pressure_deficit',
            'dew_point_temperature',
            'pressure',
            'pressure_sea_level',
            'barometric_tendency',
            'soil_surface_alco_temperature',
            'soil_surface_max_temperature',
            'air_temperature_max_before',
            'air_max_temperature',
            'weather_before',
            'weather',
            'air_temperature_wet_bulb_qual_1',
            'barometric_tendency_characteristic',
            'precipitation',
            'snow_coverage_near_station',
            'snow_coverage_route',
            'ice_crust_route',
            'snow_height_aver',
            'snow_density_aver',
            'ice_crust_aver',
            'water_total',
            'snow_coverage_charact',
            'snow_charact',
            'snow_height',
            'snow_coverage_station',
            'temperature_240cm',
            'precipitation_observed',
            'precipitation_corrected',
            'sunshine_hours',
            'delta_temp20_80',
            'delta_temp40_120',
            'delta_temp160_320'

]

target = [ 
            'delta_stage_max',
]

len(features)

68

In [40]:
len (['year',
            'month',
            'day',
            'lat',
            'lon',
            'distance_from_source',
            'drainage_area',
            'z_null',
            'aet_12',
            'aet_11',
            'aet_10',
            'aet_9',
            'aet_8',
            'aet_7',
            'aet_6',
            'aet_5',
            'aet_4',
            'aet_3',
            'aet_2',
            'aet_1',
            'Cm',
            'J',
            'K',
            'N',
            'O',
            'X',
            'Z',])

27

In [54]:
pred_model1 = model1.predict(TRAIN[features[:27]])
pred_model2 = model2.predict(TRAIN[features])

In [57]:
pred_test1 = model1.predict(TEST[features[:27]])
pred_test2 = model2.predict(TEST[features])

In [154]:
TRAIN['pred_model1'] = pred_model1
TRAIN['pred_model2'] = pred_model2
TEST['pred_model1'] = pred_test1
TEST['pred_model2'] = pred_test2

In [155]:
fe = [
    'pred_model1',
    'pred_model2'
    ]

ft = [
    'pred_test1',
    'pred_test2'
    ]

In [ ]:
f1 = features[:27]
f1.append('pred_model1')
f1.append('pred_model2')

f2 = features
f2.append('pred_model1')
f2.append('pred_model2')

In [105]:
X = TRAIN[fe]
y = TRAIN[target]

In [170]:
from sklearn.ensemble import GradientBoostingRegressor
reg = GradientBoostingRegressor(random_state=42, 
                                max_depth=2,
                                learning_rate=0.1,
                                n_estimators=1000,
                                verbose=2
                               )

In [ ]:
reg.fit(TRAIN[fe], TRAIN[target])

/home/ulyumdzhi/.local/lib/python3.8/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

      Iter       Train Loss   Remaining Time
         1         980.0526            5.26m
         2         970.0230            5.31m
         3         961.7621            5.14m
         4         954.3918            4.91m
         5         947.7459            4.86m
         6         942.3010            4.93m
         7         938.1151            4.91m
         8         933.9667            4.80m
         9         930.3869            4.77m
        10         927.4143            4.80m
        11         924.6088            4.73m
        12         922.4065            4.68m
        13         920.1790            4.65m
        14         918.0623            4.61m
        15         916.5385            4.55m
        16         914.8739            4.53m
        17         913.4805            4.50m
        18         911.8415            4.49m
        19         910.6231            4.48m
        20         909.6780            4.48m
        21         908.8624            4.46m
        22         907.9602            4.47m
        23         907.2020            4.49m
        24         906.5574            4.52m
        25         905.9067            4.51m
        26         905.3424            4.49m
        27         904.8327            4.49m
        28         904.3712            4.48m
        29         903.9701            4.46m
        30         903.6066            4.45m
        31         903.2322            4.44m
        32         902.9096            4.42m
        33         902.5072            4.40m
        34         902.2298            4.38m
        35         890.8042            4.38m
        36         890.5234            4.37m
        37         890.2826            4.37m
        38         880.9322            4.37m
        39         880.6371            4.35m
        40         880.4707            4.34m
        41         872.8804            4.33m
        42         872.6283            4.31m
        43         872.4396            4.30m
        44         872.2694            4.30m
        45         872.0973            4.28m
        46         871.9810            4.29m
        47         865.8497            4.28m
        48         865.6726            4.27m
        49         865.4686            4.26m
        50         860.5219            4.26m
        51         860.1427            4.26m
        52         860.0077            4.26m
        53         859.8458            4.26m
        54         858.3514            4.25m
        55         854.6122            4.25m
        56         854.3243            4.24m
        57         854.0966            4.24m
        58         853.9542            4.24m
        59         850.9292            4.24m
        60         850.7489            4.24m
        61         850.6070            4.23m
        62         850.4917            4.22m
        63         850.1601            4.22m
        64         850.0894            4.21m
        65         849.9727            4.20m
        66         849.7105            4.19m
        67         849.5683            4.19m
        68         849.4560            4.18m
        69         849.2109            4.17m
        70         846.7650            4.17m
        71         846.5346            4.16m
        72         846.4326            4.16m
        73         846.3465            4.15m
        74         846.2268            4.15m
        75         846.1737            4.16m
        76         846.0999            4.15m
        77         845.9910            4.15m
        78         845.9096            4.14m
        79         845.4706            4.13m
        80         845.4261            4.12m
        81         843.4432            4.12m
        82         843.2517            4.11m
        83         843.0450            4.11m
        84         842.9521            4.10m
        85         842.7767            4.10m
        86         842.7145            4.09m
        87         842.1946            4.08m
        88         842.1600            4.08m
        89         841.9453            4.08m
        90         840.2731            4.07m
        91         839.9213            4.06m
        92         839.8473            4.06m
        93         839.7406            4.05m
        94         838.3872            4.05m
        95         838.2195            4.05m
        96         838.1735            4.04m
        97         838.0221            4.03m
        98         837.9961            4.03m
        99         837.7839            4.02m
       100         837.7225            4.02m
       101         837.6781            4.01m
       102         837.5337            4.00m
       103         837.4155            4.00m
       104         836.3218            3.99m
       105         836.1856            3.98m
       106         836.0993            3.98m
       107         836.0000            3.97m
       108         835.9770            3.96m
       109         835.9131            3.96m
       110         835.0273            3.95m
       111         834.8630            3.94m
       112         834.7938            3.94m
       113         834.7033            3.93m
       114         834.5582            3.92m
       115         834.4488            3.92m
       116         834.2217            3.91m
       117         834.0055            3.90m
       118         833.7191            3.90m
       119         833.6029            3.90m
       120         833.4357            3.89m
       121         833.2498            3.89m
       122         832.4313            3.88m
       123         832.2846            3.88m
       124         832.2389            3.88m
       125         832.2007            3.88m
       126         831.5381            3.87m
       127         829.8387            3.87m
       128         818.9008            3.87m
       129         818.6668            3.86m
       130         818.6473            3.86m
       131         818.6281            3.86m
       132         818.5538            3.85m
       133         818.4341            3.85m
       134         818.4161            3.84m
       135         818.3743            3.84m
       136         817.6716            3.84m
       137         817.5810            3.84m
       138         817.4551            3.84m
       139         816.8872            3.84m
       140         816.8539            3.83m
       141         816.7018            3.83m
       142         816.1658            3.82m
       143         816.0504            3.82m
       144         815.9872            3.81m
       145         815.9135            3.81m
       146         815.7984            3.81m
       147         815.6682            3.80m
       148         815.2346            3.80m
       149         815.1990            3.79m
       150         815.1705            3.79m
       151         815.0700            3.78m
       152         815.0334            3.78m
       153         815.0201            3.77m
       154         814.9464            3.76m
       155         814.9321            3.76m
       156         814.9025            3.75m
       157         814.8151            3.74m
       158         814.7410            3.74m
       159         814.7230            3.73m
       160         805.8771            3.73m
       161         805.7459            3.72m
       162         805.7225            3.72m
       163         805.6815            3.71m
       164         805.5773            3.71m
       165         805.4898            3.70m
       166         805.4048            3.70m
       167         805.3401            3.69m
       168         805.2519            3.69m
       169         805.0665            3.68m
       170         805.0515            3.68m
       171         805.0279            3.68m
       172         804.9694            3.67m
       173         804.7863            3.67m
       174         804.6964            3.66m
       175         804.2789            3.66m
       176         804.2014            3.66m
       177         803.8526            3.65m
       178         803.7895            3.65m
       179         803.7782            3.65m
       180         803.7562            3.64m
       181         803.6066            3.64m
       182         803.3308            3.63m

       183         803.1811            3.62m
       184         803.0969            3.62m
       185         802.9367            3.61m
       186         802.8697            3.61m
       187         802.7401            3.61m
       188         802.6746            3.60m
       189         795.5116            3.60m
       190         795.4979            3.59m
       191         795.4839            3.59m
       192         795.4414            3.58m
       193         794.9820            3.58m
       194         794.6436            3.57m
       195         794.4941            3.57m
       196         794.4824            3.56m
       197         794.4211            3.56m
       198         794.2784            3.55m
       199         794.0554            3.55m
       200         793.9861            3.54m
       201         793.6142            3.54m
       202         793.4901            3.53m
       203         793.4156            3.53m
       204         793.3900            3.52m
       205         793.3707            3.52m
       206         793.3200            3.52m
       207         793.2657            3.51m
       208         793.1058            3.51m
       209         792.8038            3.50m
       210         792.7100            3.50m
       211         792.5933            3.50m
       212         786.7936            3.49m
       213         786.7830            3.49m
       214         786.6666            3.49m
       215         786.4868            3.49m
       216         786.4228            3.48m
       217         786.3655            3.48m
       218         786.2953            3.48m
       219         786.1606            3.47m
       220         786.0390            3.47m
       221         785.9178            3.47m
       222         785.8882            3.46m
       223         785.8386            3.46m
       224         785.7312            3.45m
       225         785.6864            3.45m
       226         785.6688            3.45m
       227         785.6476            3.44m
       228         780.9543            3.44m
       229         780.9165            3.43m
       230         780.8234            3.43m
       231         780.7732            3.42m
       232         780.6688            3.42m
       233         780.6321            3.41m
       234         780.5534            3.41m
       235         780.4077            3.41m
       236         780.1416            3.40m
       237         780.0765            3.39m
       238         779.9606            3.39m
       239         779.9528            3.39m
       240         779.9378            3.38m
       241         779.9262            3.38m
       242         779.8443            3.37m
       243         779.7960            3.36m
       244         779.7351            3.36m
       245         779.6525            3.36m
       246         779.6195            3.35m
       247         779.6069            3.35m
       248         779.5121            3.34m
       249         779.3704            3.34m
       250         779.1248            3.33m
       251         779.0098            3.33m
       252         778.9771            3.32m
       253         778.7785            3.32m
       254         778.6856            3.31m
       255         778.4698            3.31m
       256         778.3657            3.30m
       257         778.3439            3.30m
       258         778.1732            3.29m
       259         778.1062            3.29m
       260         777.9878            3.28m
       261         777.8126            3.28m
       262         777.7458            3.27m
       263         777.6717            3.27m
       264         773.8721            3.26m
       265         773.8635            3.26m
       266         773.7972            3.25m
       267         773.5267            3.25m
       268         773.3812            3.25m
       269         773.3338            3.24m
       270         773.3275            3.24m
       271         773.2356            3.23m
       272         773.2015            3.23m
       273         773.0675            3.22m
       274         772.9319            3.22m
       275         772.8884            3.21m
       276         772.8335            3.21m
       277         772.7479            3.20m
       278         772.6354            3.20m
       279         772.5104            3.20m
       280         772.3989            3.19m
       281         772.3680            3.18m
       282         772.3010            3.18m
       283         772.2918            3.17m
       284         772.1295            3.17m
       285         771.9875            3.16m
       286         771.9195            3.16m
       287         771.8226            3.16m
       288         771.7559            3.15m
       289         771.6862            3.15m
       290         771.6774            3.14m
       291         771.6487            3.14m
       292         771.5699            3.13m
       293         771.5438            3.13m
       294         771.5302            3.12m
       295         771.5212            3.12m
       296         771.4727            3.11m
       297         771.4568            3.11m
       298         771.4356            3.10m
       299         771.3038            3.10m
       300         771.2191            3.09m
       301         771.1820            3.09m
       302         771.1275            3.08m
       303         771.0314            3.08m
       304         770.8356            3.07m
       305         770.7684            3.07m
       306         770.6754            3.06m
       307         770.5167            3.06m
       308         770.4222            3.06m
       309         770.3870            3.05m
       310         770.2636            3.05m
       311         770.1856            3.04m

In [ ]:
preds = reg.predict(TEST[ft])

In [168]:
test = pd.read_csv('./DATA/cp4_test.csv')
test.columns

Index(['year', 'station_id', 'month', 'day', 'date', 'delta_stage_max'], dtype='object')

In [ ]:
TEST['delta_stage_max'] = preds
TEST['date'] = test['date']
TEST['station_id'] = test['station_id']
TEST[[ 'year', 'month', 'day', 'station_id', 'date', 'delta_stage_max']].to_csv('submit_reg.csv', index=False)